version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      javascript-dependencies:
        patterns: ["*"]
  - package-ecosystem: gradle
    directory: /apps/mobile/android
    schedule:
      interval: weekly
