import type { ExerciseDefinition } from "@pockettrainer/contracts";

import {
  DEFAULT_CALIBRATION,
  DEFAULT_FEEDBACK_TIMING,
  DEFAULT_SCORE_WEIGHTS,
  deepFreeze,
} from "./shared.js";

export const BODY_SQUAT_DEFINITION = deepFreeze({
  exerciseKey: "body_squat",
  exerciseDefinitionVersion: 1,
  schemaVersion: 1,
  scoringVersion: 1,
  poseModelVersion: "mediapipe-pose-landmarker-lite@1",
  minimumAppVersion: "0.1.0",
  rollbackExerciseDefinitionVersion: null,
  displayName: {
    "id-ID": "Squat Berat Badan",
    "en-US": "Body Squat",
  },
  category: "strength",
  mode: "repetition",
  cameraView: "side",
  requiredLandmarks: [
    "left_shoulder",
    "right_shoulder",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
  ],
  calibration: DEFAULT_CALIBRATION,
  states: [
    {
      id: "ready",
      predicates: [{ metric: "knee_angle", operator: "gt", value: 155, hysteresis: 4 }],
      predicateMode: "all",
      minimumDurationMs: 400,
      allowedPreviousStates: ["complete"],
      terminal: false,
    },
    {
      id: "descending",
      predicates: [{ metric: "knee_angular_velocity", operator: "lt", value: -12, hysteresis: 2 }],
      predicateMode: "all",
      minimumDurationMs: 80,
      allowedPreviousStates: ["ready"],
      terminal: false,
    },
    {
      id: "bottom",
      predicates: [{ metric: "knee_angle", operator: "between", value: 70, maximum: 110, hysteresis: 4 }],
      predicateMode: "all",
      minimumDurationMs: 100,
      allowedPreviousStates: ["descending"],
      terminal: false,
    },
    {
      id: "ascending",
      predicates: [{ metric: "knee_angular_velocity", operator: "gt", value: 12, hysteresis: 2 }],
      predicateMode: "all",
      minimumDurationMs: 80,
      allowedPreviousStates: ["bottom"],
      terminal: false,
    },
    {
      id: "complete",
      predicates: [{ metric: "knee_angle", operator: "gt", value: 155, hysteresis: 4 }],
      predicateMode: "all",
      minimumDurationMs: 180,
      allowedPreviousStates: ["ascending"],
      terminal: true,
    },
  ],
  maximumRepDurationMs: 8_000,
  trackingLossResetMs: 1_200,
  rules: [
    {
      id: "squat_depth",
      phases: ["bottom"],
      metric: "knee_angle",
      idealRange: { minimum: 70, maximum: 110 },
      hardRange: { minimum: 55, maximum: 135 },
      weight: 0.35,
      phaseWeight: 1.4,
      critical: true,
      feedbackKey: "squat.depth",
    },
    {
      id: "squat_torso_control",
      phases: ["descending", "bottom", "ascending"],
      metric: "torso_lean",
      idealRange: { minimum: 0, maximum: 35 },
      hardRange: { minimum: 0, maximum: 55 },
      weight: 0.3,
      phaseWeight: 1.2,
      critical: true,
      feedbackKey: "squat.chestUpright",
    },
    {
      id: "squat_knee_control",
      phases: ["descending", "bottom", "ascending"],
      metric: "front_knee_ankle_offset",
      idealRange: { minimum: 0, maximum: 0.12 },
      hardRange: { minimum: 0, maximum: 0.25 },
      weight: 0.2,
      phaseWeight: 1.1,
      critical: true,
      feedbackKey: "squat.kneeTrack",
    },
    {
      id: "squat_stability",
      phases: ["descending", "bottom", "ascending"],
      metric: "center_displacement",
      idealRange: { minimum: 0, maximum: 0.08 },
      hardRange: { minimum: 0, maximum: 0.2 },
      weight: 0.15,
      phaseWeight: 1,
      critical: false,
      feedbackKey: "squat.steady",
    },
  ],
  scoreWeights: DEFAULT_SCORE_WEIGHTS,
  feedback: [
    {
      key: "squat.depth",
      ruleId: "squat_depth",
      severity: "important",
      message: {
        "id-ID": "Turunkan pinggul sedikit lagi",
        "en-US": "Lower your hips slightly more",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "squat.chestUpright",
      ruleId: "squat_torso_control",
      severity: "important",
      message: {
        "id-ID": "Jaga dada tetap lebih tegak",
        "en-US": "Keep your chest more upright",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "squat.kneeTrack",
      ruleId: "squat_knee_control",
      severity: "safety",
      message: {
        "id-ID": "Arahkan lutut mengikuti jari kaki",
        "en-US": "Keep your knee tracking over your toes",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "squat.steady",
      ruleId: "squat_stability",
      severity: "coaching",
      message: {
        "id-ID": "Bergerak dengan lebih stabil",
        "en-US": "Move with a little more control",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
  ],
  progression: {
    easierVariationKey: "chair_squat",
    harderVariationKey: "pause_squat",
    requiredEquipment: ["none"],
    requiredCapabilities: { lower_body_control: 40 },
    contraindicationTags: ["knee_flexion"],
  },
} satisfies ExerciseDefinition);
