import type { ExerciseDefinition } from "@pockettrainer/contracts";

import {
  DEFAULT_CALIBRATION,
  DEFAULT_FEEDBACK_TIMING,
  DEFAULT_SCORE_WEIGHTS,
  deepFreeze,
} from "./shared.js";

export const INCLINE_PUSH_UP_DEFINITION = deepFreeze({
  exerciseKey: "incline_push_up",
  exerciseDefinitionVersion: 1,
  schemaVersion: 1,
  scoringVersion: 1,
  metricSpecificationVersion: 1,
  poseModelVersion: "mediapipe-pose-landmarker-lite@1",
  minimumAppVersion: "0.1.0",
  rollbackExerciseDefinitionVersion: null,
  displayName: {
    "id-ID": "Push-up Bertumpu",
    "en-US": "Incline Push-up",
  },
  category: "strength",
  mode: "repetition",
  cameraView: "side",
  requiredLandmarks: [
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hip",
    "right_hip",
    "left_ankle",
    "right_ankle",
  ],
  calibration: { ...DEFAULT_CALIBRATION, minimumBodyCoverage: 0.76 },
  states: [
    {
      id: "ready",
      predicates: [{ metric: "elbow_angle", operator: "gt", value: 155, hysteresis: 5 }],
      predicateMode: "all",
      minimumDurationMs: 400,
      allowedPreviousStates: ["complete"],
      terminal: false,
    },
    {
      id: "descending",
      predicates: [{ metric: "elbow_angular_velocity", operator: "lt", value: -10, hysteresis: 2 }],
      predicateMode: "all",
      minimumDurationMs: 80,
      allowedPreviousStates: ["ready"],
      terminal: false,
    },
    {
      id: "bottom",
      predicates: [{ metric: "elbow_angle", operator: "between", value: 70, maximum: 105, hysteresis: 5 }],
      predicateMode: "all",
      minimumDurationMs: 100,
      allowedPreviousStates: ["descending"],
      terminal: false,
    },
    {
      id: "ascending",
      predicates: [{ metric: "elbow_angular_velocity", operator: "gt", value: 10, hysteresis: 2 }],
      predicateMode: "all",
      minimumDurationMs: 80,
      allowedPreviousStates: ["bottom"],
      terminal: false,
    },
    {
      id: "complete",
      predicates: [{ metric: "elbow_angle", operator: "gt", value: 155, hysteresis: 5 }],
      predicateMode: "all",
      minimumDurationMs: 180,
      allowedPreviousStates: ["ascending"],
      terminal: true,
    },
  ],
  stateMachine: {
    initialStateId: "ready",
    resetStateId: "ready",
    transitionPriority: ["complete", "ascending", "bottom", "descending", "ready"],
    invalidTransitionBehavior: "retain_current_state",
  },
  maximumRepDurationMs: 8_000,
  trackingLossResetMs: 1_200,
  rules: [
    {
      id: "pushup_body_line",
      phases: ["ready", "descending", "bottom", "ascending", "complete"],
      metric: "body_line_deviation",
      idealRange: { minimum: 0, maximum: 12 },
      hardRange: { minimum: 0, maximum: 28 },
      weight: 0.35,
      phaseWeight: 1.3,
      critical: true,
      feedbackKey: "pushup.hipsAligned",
    },
    {
      id: "pushup_depth",
      phases: ["bottom"],
      metric: "elbow_angle",
      idealRange: { minimum: 70, maximum: 105 },
      hardRange: { minimum: 55, maximum: 130 },
      weight: 0.3,
      phaseWeight: 1.4,
      critical: true,
      feedbackKey: "pushup.depth",
    },
    {
      id: "pushup_shoulder_control",
      phases: ["descending", "bottom", "ascending"],
      metric: "shoulder_tilt",
      idealRange: { minimum: -8, maximum: 8 },
      hardRange: { minimum: -20, maximum: 20 },
      weight: 0.2,
      phaseWeight: 1.1,
      critical: false,
      feedbackKey: "pushup.shouldersLevel",
    },
    {
      id: "pushup_tempo",
      phases: ["descending", "ascending"],
      metric: "elbow_angular_velocity",
      idealRange: { minimum: -70, maximum: 70 },
      hardRange: { minimum: -140, maximum: 140 },
      weight: 0.15,
      phaseWeight: 1,
      critical: false,
      feedbackKey: "pushup.controlTempo",
    },
  ],
  scoreWeights: DEFAULT_SCORE_WEIGHTS,
  feedback: [
    {
      key: "pushup.hipsAligned",
      ruleId: "pushup_body_line",
      severity: "safety",
      message: {
        "id-ID": "Jaga pinggul tetap sejajar",
        "en-US": "Keep your hips aligned",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "pushup.depth",
      ruleId: "pushup_depth",
      severity: "important",
      message: {
        "id-ID": "Turunkan dada sedikit lagi",
        "en-US": "Lower your chest slightly more",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "pushup.shouldersLevel",
      ruleId: "pushup_shoulder_control",
      severity: "coaching",
      message: {
        "id-ID": "Jaga kedua bahu tetap sejajar",
        "en-US": "Keep both shoulders level",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "pushup.controlTempo",
      ruleId: "pushup_tempo",
      severity: "coaching",
      message: {
        "id-ID": "Perlambat gerakanmu",
        "en-US": "Slow the movement down",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
  ],
  progression: {
    easierVariationKey: "wall_push_up",
    harderVariationKey: "knee_push_up",
    requiredEquipment: ["chair"],
    requiredCapabilities: { upper_body_control: 35, core_stability: 30 },
    contraindicationTags: ["wrist_loading", "shoulder_loading"],
  },
} satisfies ExerciseDefinition);
