import type { ExerciseDefinition } from "@pockettrainer/contracts";

import {
  DEFAULT_CALIBRATION,
  DEFAULT_FEEDBACK_TIMING,
  DEFAULT_SCORE_WEIGHTS,
  deepFreeze,
} from "./shared.js";

export const TREE_POSE_DEFINITION = deepFreeze({
  exerciseKey: "tree_pose",
  exerciseDefinitionVersion: 1,
  schemaVersion: 1,
  scoringVersion: 1,
  poseModelVersion: "mediapipe-pose-landmarker-full@1",
  minimumAppVersion: "0.1.0",
  rollbackExerciseDefinitionVersion: null,
  displayName: {
    "id-ID": "Pose Pohon",
    "en-US": "Tree Pose",
  },
  category: "yoga",
  mode: "hold",
  cameraView: "front",
  requiredLandmarks: [
    "left_shoulder",
    "right_shoulder",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
    "left_foot_index",
    "right_foot_index",
  ],
  calibration: DEFAULT_CALIBRATION,
  states: [
    {
      id: "searching",
      predicates: [{ metric: "pose_confidence", operator: "gte", value: 0.65 }],
      predicateMode: "all",
      minimumDurationMs: 0,
      allowedPreviousStates: ["holding"],
      terminal: false,
    },
    {
      id: "aligned",
      predicates: [
        { metric: "single_leg_stability", operator: "gte", value: 0.72, hysteresis: 0.05 },
        { metric: "raised_knee_lateral_rotation", operator: "gte", value: 28, hysteresis: 4 },
      ],
      predicateMode: "all",
      minimumDurationMs: 500,
      allowedPreviousStates: ["searching", "holding"],
      terminal: false,
    },
    {
      id: "holding",
      predicates: [
        { metric: "single_leg_stability", operator: "gte", value: 0.72, hysteresis: 0.08 },
        { metric: "raised_knee_lateral_rotation", operator: "gte", value: 28, hysteresis: 5 },
        { metric: "hip_tilt", operator: "between", value: -12, maximum: 12, hysteresis: 3 },
      ],
      predicateMode: "all",
      minimumDurationMs: 500,
      allowedPreviousStates: ["aligned"],
      terminal: false,
    },
    {
      id: "completed",
      predicates: [
        { metric: "single_leg_stability", operator: "gte", value: 0.72, hysteresis: 0.08 },
        { metric: "raised_knee_lateral_rotation", operator: "gte", value: 28, hysteresis: 5 },
        { metric: "hip_tilt", operator: "between", value: -12, maximum: 12, hysteresis: 3 },
      ],
      predicateMode: "all",
      minimumDurationMs: 15_000,
      allowedPreviousStates: ["holding"],
      terminal: true,
    },
  ],
  targetHoldDurationMs: 15_000,
  trackingLossResetMs: 2_500,
  rules: [
    {
      id: "tree_balance",
      phases: ["aligned", "holding"],
      metric: "single_leg_stability",
      idealRange: { minimum: 0.82, maximum: 1 },
      hardRange: { minimum: 0.5, maximum: 1 },
      weight: 0.4,
      phaseWeight: 1.4,
      critical: true,
      feedbackKey: "tree.fixedPoint",
    },
    {
      id: "tree_knee_open",
      phases: ["aligned", "holding"],
      metric: "raised_knee_lateral_rotation",
      idealRange: { minimum: 35, maximum: 80 },
      hardRange: { minimum: 15, maximum: 100 },
      weight: 0.25,
      phaseWeight: 1.1,
      critical: false,
      feedbackKey: "tree.openKnee",
    },
    {
      id: "tree_hips_level",
      phases: ["aligned", "holding"],
      metric: "hip_tilt",
      idealRange: { minimum: -6, maximum: 6 },
      hardRange: { minimum: -18, maximum: 18 },
      weight: 0.2,
      phaseWeight: 1,
      critical: false,
      feedbackKey: "tree.standTall",
    },
    {
      id: "tree_sway",
      phases: ["holding"],
      metric: "center_displacement",
      idealRange: { minimum: 0, maximum: 0.05 },
      hardRange: { minimum: 0, maximum: 0.2 },
      weight: 0.15,
      phaseWeight: 1.2,
      critical: false,
      feedbackKey: "tree.steady",
    },
  ],
  scoreWeights: DEFAULT_SCORE_WEIGHTS,
  feedback: [
    {
      key: "tree.fixedPoint",
      ruleId: "tree_balance",
      severity: "important",
      message: {
        "id-ID": "Tatap satu titik dan stabilkan tubuh",
        "en-US": "Focus on a fixed point and steady your body",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "tree.openKnee",
      ruleId: "tree_knee_open",
      severity: "coaching",
      message: { "id-ID": "Buka lutut ke samping perlahan", "en-US": "Gently open your knee to the side" },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "tree.standTall",
      ruleId: "tree_hips_level",
      severity: "coaching",
      message: { "id-ID": "Tegakkan tubuh dan rilekskan bahu", "en-US": "Stand tall and relax your shoulders" },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "tree.steady",
      ruleId: "tree_sway",
      severity: "coaching",
      message: { "id-ID": "Kurangi goyangan secara perlahan", "en-US": "Gently reduce the sway" },
      ...DEFAULT_FEEDBACK_TIMING,
    },
  ],
  progression: {
    easierVariationKey: "kickstand_tree_pose",
    harderVariationKey: "tree_pose_eyes_closed",
    requiredEquipment: ["yoga_mat"],
    requiredCapabilities: { balance: 40, lower_body_control: 30 },
    contraindicationTags: ["single_leg_balance"],
  },
} satisfies ExerciseDefinition);
