import type { ExerciseDefinition } from "@pockettrainer/contracts";

import {
  DEFAULT_CALIBRATION,
  DEFAULT_FEEDBACK_TIMING,
  DEFAULT_SCORE_WEIGHTS,
  deepFreeze,
} from "./shared.js";

export const WARRIOR_II_DEFINITION = deepFreeze({
  exerciseKey: "warrior_ii",
  exerciseDefinitionVersion: 1,
  schemaVersion: 1,
  scoringVersion: 1,
  metricSpecificationVersion: 1,
  poseModelVersion: "mediapipe-pose-landmarker-full@1",
  minimumAppVersion: "0.1.0",
  rollbackExerciseDefinitionVersion: null,
  displayName: {
    "id-ID": "Prajurit II",
    "en-US": "Warrior II",
  },
  category: "yoga",
  mode: "hold",
  cameraView: "front",
  requiredLandmarks: [
    "left_shoulder",
    "right_shoulder",
    "left_elbow",
    "right_elbow",
    "left_wrist",
    "right_wrist",
    "left_hip",
    "right_hip",
    "left_knee",
    "right_knee",
    "left_ankle",
    "right_ankle",
  ],
  calibration: { ...DEFAULT_CALIBRATION, minimumBodyCoverage: 0.88 },
  states: [
    {
      id: "searching",
      predicates: [{ metric: "pose_confidence", operator: "gte", value: 0.65 }],
      predicateMode: "all",
      minimumDurationMs: 0,
      allowedPreviousStates: [],
      terminal: false,
    },
    {
      id: "aligned",
      predicates: [
        { metric: "arm_horizontal_deviation_left", operator: "lte", value: 14, hysteresis: 3 },
        { metric: "arm_horizontal_deviation_right", operator: "lte", value: 14, hysteresis: 3 },
        { metric: "shoulder_tilt", operator: "between", value: -8, maximum: 8, hysteresis: 2 },
      ],
      predicateMode: "all",
      minimumDurationMs: 500,
      allowedPreviousStates: ["searching"],
      terminal: false,
    },
    {
      id: "holding",
      predicates: [
        { metric: "arm_horizontal_deviation_left", operator: "lte", value: 14, hysteresis: 4 },
        { metric: "arm_horizontal_deviation_right", operator: "lte", value: 14, hysteresis: 4 },
        { metric: "front_knee_ankle_offset", operator: "lte", value: 0.12, hysteresis: 0.03 },
      ],
      predicateMode: "all",
      minimumDurationMs: 500,
      allowedPreviousStates: ["aligned"],
      terminal: false,
    },
    {
      id: "completed",
      predicates: [
        { metric: "arm_horizontal_deviation_left", operator: "lte", value: 14, hysteresis: 4 },
        { metric: "arm_horizontal_deviation_right", operator: "lte", value: 14, hysteresis: 4 },
        { metric: "front_knee_ankle_offset", operator: "lte", value: 0.12, hysteresis: 0.03 },
        { metric: "valid_hold_duration_ms", operator: "gte", value: 20_000 },
      ],
      predicateMode: "all",
      minimumDurationMs: 0,
      allowedPreviousStates: ["holding"],
      terminal: true,
    },
  ],
  stateMachine: {
    initialStateId: "searching",
    resetStateId: "searching",
    transitionPriority: ["completed", "holding", "aligned", "searching"],
    invalidTransitionBehavior: "retain_current_state",
    holdAccumulator: {
      activeStateId: "holding",
      pauseWhenActivePredicatesFail: true,
      completionMetric: "valid_hold_duration_ms",
      resetAfterTrackingLossMs: 2_500,
      resetAfterAlignmentLossMs: 5_000,
    },
  },
  targetHoldDurationMs: 20_000,
  trackingLossResetMs: 2_500,
  rules: [
    {
      id: "warrior_left_arm",
      phases: ["aligned", "holding"],
      metric: "arm_horizontal_deviation_left",
      idealRange: { minimum: 0, maximum: 10 },
      hardRange: { minimum: 0, maximum: 28 },
      weight: 0.25,
      phaseWeight: 1.2,
      critical: true,
      feedbackKey: "warrior.raiseLeftArm",
    },
    {
      id: "warrior_right_arm",
      phases: ["aligned", "holding"],
      metric: "arm_horizontal_deviation_right",
      idealRange: { minimum: 0, maximum: 10 },
      hardRange: { minimum: 0, maximum: 28 },
      weight: 0.25,
      phaseWeight: 1.2,
      critical: true,
      feedbackKey: "warrior.raiseRightArm",
    },
    {
      id: "warrior_front_knee",
      phases: ["aligned", "holding"],
      metric: "front_knee_ankle_offset",
      idealRange: { minimum: 0, maximum: 0.12 },
      hardRange: { minimum: 0, maximum: 0.28 },
      weight: 0.3,
      phaseWeight: 1.4,
      critical: true,
      feedbackKey: "warrior.kneeTrack",
    },
    {
      id: "warrior_stability",
      phases: ["holding"],
      metric: "center_displacement",
      idealRange: { minimum: 0, maximum: 0.06 },
      hardRange: { minimum: 0, maximum: 0.18 },
      weight: 0.2,
      phaseWeight: 1,
      critical: false,
      feedbackKey: "warrior.steady",
    },
  ],
  scoreWeights: DEFAULT_SCORE_WEIGHTS,
  feedback: [
    {
      key: "warrior.raiseLeftArm",
      ruleId: "warrior_left_arm",
      severity: "important",
      message: { "id-ID": "Angkat lengan kiri", "en-US": "Raise your left arm" },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "warrior.raiseRightArm",
      ruleId: "warrior_right_arm",
      severity: "important",
      message: { "id-ID": "Angkat lengan kanan", "en-US": "Raise your right arm" },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "warrior.kneeTrack",
      ruleId: "warrior_front_knee",
      severity: "safety",
      message: {
        "id-ID": "Sejajarkan lutut depan dengan pergelangan kaki",
        "en-US": "Align your front knee over your ankle",
      },
      ...DEFAULT_FEEDBACK_TIMING,
    },
    {
      key: "warrior.steady",
      ruleId: "warrior_stability",
      severity: "coaching",
      message: { "id-ID": "Tahan posisi dengan stabil", "en-US": "Hold the pose steadily" },
      ...DEFAULT_FEEDBACK_TIMING,
    },
  ],
  progression: {
    easierVariationKey: "supported_warrior_ii",
    harderVariationKey: "reverse_warrior",
    requiredEquipment: ["yoga_mat"],
    requiredCapabilities: { balance: 35, mobility: 35, lower_body_control: 35 },
    contraindicationTags: ["knee_flexion", "shoulder_overhead"],
  },
} satisfies ExerciseDefinition);
