import React, {useEffect, useRef, useState} from 'react';
import {Animated, ImageBackground, Pressable, ScrollView, StyleSheet, Text, View} from 'react-native';
import {BrandMark} from '../components/BrandMark';
import {ProgressRing} from '../components/ProgressRing';
import {colors, radius, spacing, type} from '../design/tokens';

type HomeScreenProps = {onStartLesson: () => void};

export function HomeScreen({onStartLesson}: HomeScreenProps) {
  const entry = useRef(new Animated.Value(0)).current;
  const [showReady, setShowReady] = useState(false);
  useEffect(() => {Animated.timing(entry, {toValue: 1, duration: 480, useNativeDriver: true}).start();}, [entry]);

  return <Animated.View style={[styles.flex, {opacity: entry, transform: [{translateY: entry.interpolate({inputRange: [0, 1], outputRange: [12, 0]})}]}]}>
    <ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}>
      <View style={styles.topBar}><BrandMark /><Pressable accessibilityLabel="Open notifications" accessibilityRole="button" style={styles.notificationButton}><View style={styles.notificationDot} /><Text style={styles.notificationGlyph}>◌</Text></Pressable></View>
      <View style={styles.greeting}><Text style={styles.eyebrow}>SELAMAT PAGI, RAKA</Text><Text style={styles.title}>Make today{`\n`}count.</Text><Text style={styles.subtitle}>Small, consistent sessions build the strongest you.</Text></View>
      <ImageBackground imageStyle={styles.heroImage} source={require('../assets/images/home-hero.jpg')} style={styles.hero}>
        <View style={styles.heroScrim} /><View style={styles.heroContent}>
          <View style={styles.heroBadge}><View style={styles.liveDot} /><Text style={styles.heroBadgeText}>TODAY’S LESSON</Text></View>
          <View><Text style={styles.heroKicker}>FOUNDATION / 02</Text><Text style={styles.heroTitle}>Own your squat.</Text><Text style={styles.heroMeta}>8 min  ·  Lower body  ·  No equipment</Text></View>
          <Pressable accessibilityLabel="Continue squat lesson" accessibilityRole="button" onPress={onStartLesson} style={({pressed}) => [styles.primaryButton, pressed && styles.buttonPressed]}><Text style={styles.primaryButtonText}>Continue lesson</Text><Text style={styles.primaryButtonArrow}>↗</Text></Pressable>
        </View>
      </ImageBackground>
      <View style={styles.sectionHeader}><Text style={styles.sectionTitle}>Your rhythm</Text><Text style={styles.sectionMeta}>Week 03</Text></View>
      <View style={styles.rhythmRow}><View style={styles.rhythmCard}><ProgressRing caption="STREAK" label="7" size={98} stroke={7} value={70} /><Text style={styles.rhythmHint}>days in motion</Text></View><View style={styles.rhythmCard}><ProgressRing caption="XP TODAY" label="240" size={98} stroke={7} value={60} /><Text style={styles.rhythmHint}>of 400 earned</Text></View></View>
      <View style={styles.readinessCard}><View style={styles.readinessIcon}><Text style={styles.readinessGlyph}>↗</Text></View><View style={styles.readinessCopy}><Text style={styles.readinessEyebrow}>READINESS CHECK</Text><Text style={styles.readinessTitle}>{showReady ? 'You’re set for a focused 8 min.' : 'How does your body feel today?'}</Text><Text style={styles.readinessBody}>{showReady ? 'We’ll keep your next session steady and controlled.' : 'One quick check helps us keep your path safe.'}</Text></View><Pressable accessibilityLabel="Open readiness check" accessibilityRole="button" onPress={() => setShowReady(value => !value)} style={styles.chevronButton}><Text style={styles.chevron}>›</Text></Pressable></View>
      <View style={styles.pathHeader}><View><Text style={styles.sectionTitle}>Your path</Text><Text style={styles.pathSubhead}>Foundation · 4 of 12 lessons</Text></View><Text style={styles.pathProgress}>33%</Text></View>
      <View style={styles.pathTrack}><View style={styles.pathFill} /><View style={[styles.pathNode, styles.pathNodeComplete]}><Text style={styles.pathNodeText}>✓</Text></View><View style={[styles.pathNode, styles.pathNodeComplete, styles.pathNodeSecond]}><Text style={styles.pathNodeText}>✓</Text></View><View style={[styles.pathNode, styles.pathNodeCurrent, styles.pathNodeThird]}><View style={styles.pathNodeInner} /></View><View style={[styles.pathNode, styles.pathNodeLocked, styles.pathNodeFourth]}><Text style={styles.lock}>·</Text></View></View>
      <Text style={styles.pathCaption}>Next safe goal: hold a strong bottom position for 3 seconds.</Text>
    </ScrollView>
  </Animated.View>;
}

const styles = StyleSheet.create({
  flex: {flex: 1}, content: {paddingBottom: 28, paddingHorizontal: spacing.lg, paddingTop: spacing.sm},
  topBar: {alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', paddingBottom: spacing.xxl},
  notificationButton: {alignItems: 'center', borderColor: colors.border, borderRadius: 14, borderWidth: 1, height: 44, justifyContent: 'center', width: 44}, notificationGlyph: {color: colors.text, fontSize: 25, lineHeight: 28, transform: [{rotate: '-20deg'}]}, notificationDot: {backgroundColor: colors.coral, borderColor: colors.canvas, borderRadius: 4, borderWidth: 2, height: 9, position: 'absolute', right: 8, top: 7, width: 9, zIndex: 1},
  greeting: {paddingBottom: spacing.xl}, eyebrow: {...type.micro, color: colors.coral, letterSpacing: 1.2, marginBottom: spacing.sm}, title: {...type.display, color: colors.text, letterSpacing: -1.1}, subtitle: {...type.body, color: colors.secondary, marginTop: spacing.sm, maxWidth: 300},
  hero: {borderRadius: radius.card, height: 286, overflow: 'hidden'}, heroImage: {borderRadius: radius.card}, heroScrim: {backgroundColor: 'rgba(13,11,11,0.25)', bottom: 0, left: 0, position: 'absolute', right: 0, top: 0}, heroContent: {flex: 1, justifyContent: 'space-between', padding: spacing.lg}, heroBadge: {alignItems: 'center', alignSelf: 'flex-start', backgroundColor: 'rgba(13,11,11,0.72)', borderColor: 'rgba(255,247,243,0.13)', borderRadius: radius.pill, borderWidth: 1, flexDirection: 'row', gap: 7, paddingHorizontal: spacing.sm, paddingVertical: 7}, liveDot: {backgroundColor: colors.coral, borderRadius: 4, height: 7, width: 7}, heroBadgeText: {...type.micro, color: colors.text, letterSpacing: 0.4}, heroKicker: {...type.micro, color: colors.coral, letterSpacing: 1.1, marginBottom: 5}, heroTitle: {...type.h1, color: colors.text, fontSize: 28, lineHeight: 33}, heroMeta: {...type.support, color: 'rgba(255,247,243,0.78)', marginTop: 5},
  primaryButton: {alignItems: 'center', backgroundColor: colors.coral, borderRadius: radius.control, flexDirection: 'row', height: 52, justifyContent: 'space-between', paddingHorizontal: spacing.md}, buttonPressed: {opacity: 0.78, transform: [{scale: 0.99}]}, primaryButtonText: {...type.body, color: colors.canvas, fontWeight: '700'}, primaryButtonArrow: {color: colors.canvas, fontSize: 24, lineHeight: 24},
  sectionHeader: {alignItems: 'baseline', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.md, marginTop: spacing.xxl}, sectionTitle: {...type.section, color: colors.text}, sectionMeta: {...type.support, color: colors.muted}, rhythmRow: {flexDirection: 'row', gap: spacing.sm}, rhythmCard: {alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1, flex: 1, paddingBottom: spacing.md, paddingTop: spacing.md}, rhythmHint: {...type.micro, color: colors.secondary, marginTop: spacing.xs},
  readinessCard: {alignItems: 'center', backgroundColor: colors.raised, borderColor: colors.border, borderRadius: radius.card, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm, padding: spacing.md}, readinessIcon: {alignItems: 'center', backgroundColor: 'rgba(102,221,177,0.13)', borderRadius: 13, height: 42, justifyContent: 'center', width: 42}, readinessGlyph: {color: colors.mint, fontSize: 22, lineHeight: 24}, readinessCopy: {flex: 1}, readinessEyebrow: {...type.micro, color: colors.mint, letterSpacing: 0.8}, readinessTitle: {...type.card, color: colors.text, fontSize: 15, marginTop: 2}, readinessBody: {...type.support, color: colors.secondary, marginTop: 2}, chevronButton: {alignItems: 'center', height: 44, justifyContent: 'center', width: 32}, chevron: {color: colors.text, fontSize: 30, fontWeight: '300', lineHeight: 30},
  pathHeader: {alignItems: 'flex-end', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.md, marginTop: spacing.xxl}, pathSubhead: {...type.support, color: colors.secondary, marginTop: 3}, pathProgress: {...type.card, color: colors.coral}, pathTrack: {height: 48, justifyContent: 'center', marginHorizontal: spacing.xs, position: 'relative'}, pathFill: {backgroundColor: colors.coral, height: 3, left: 5, position: 'absolute', top: 23, width: '48%'}, pathNode: {alignItems: 'center', borderRadius: 14, height: 28, justifyContent: 'center', position: 'absolute', top: 9, width: 28}, pathNodeComplete: {backgroundColor: colors.coral, left: 0}, pathNodeSecond: {left: '30%'}, pathNodeCurrent: {backgroundColor: colors.canvas, borderColor: colors.coral, borderWidth: 2, left: '61%'}, pathNodeThird: {left: '61%'}, pathNodeLocked: {backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, right: 0}, pathNodeFourth: {right: 0}, pathNodeInner: {backgroundColor: colors.coral, borderRadius: 6, height: 10, width: 10}, pathNodeText: {color: colors.canvas, fontSize: 16, fontWeight: '700'}, lock: {color: colors.muted, fontSize: 20, lineHeight: 20}, pathCaption: {...type.support, color: colors.secondary, lineHeight: 21, marginBottom: spacing.lg, marginTop: spacing.sm},
});
